### ISSUE TITLE
MAX31856 works in one shot mode only

### ISSUE THREAD

**Issue by PiotrC1** [adafruit/Adafruit_MAX31856#12]
One shot mode is very time consuming - one has to wait certain time for a conversion. What's more, in a library it's fixed to 250ms. If chip works in Automatic conversion mode it's much faster.

**Comment by ladyada** [comment]
if you can add support for this and the other issue as a PR that would be awesome! note we still want to keep one-shot mode since thats much lower *power* even tho its slower :)

**Comment by PiotrC1** [comment]
OK, I will do (as a matter of fact I have already done it).
BTW. I was not aware of power considerations (what is obvoius, of course). In my case I do not care about power dissipation - I care about timing. I read my thermocouple periodically every 320ms and any delay is poinonous.

**Comment by ladyada** [comment]
great!

**Comment by OneGneissGuy** [comment]
@hjf Thank you for developing continuous modes sampling. I have not been able to get it to work however. When I call `readThermocoupleTemperature(false)`, the temperature readings aren't refreshed and the same value continues to be reported.According to the IC's  documentation I expect the `LTCBH` register to be continuously updated every 100 ms and  `readThermocoupleTemperature(true)` to give me a new value.

**Comment by plut0nium** [comment]
I strongly support this issue/feature request, when you read the temperature every second, a 250ms delay is a big waste of resources.
Another option is to have a function to explicitely put the MAX31856 in autonconvert mode (CMODE bit in CR0 register), and use `readThermocoupleTemperature(false)` as proposed in this PR to read the thermocouple conversion result anytime (up to the user).

**Comment by caternuson** [comment]
Hopefully fixed with #22
