### ISSUE TITLE
How to use more then one MAX31856 modeles?

### ISSUE THREAD

**Issue by edsonbrito** [adafruit/Adafruit_MAX31856#15]
Hi,

I´d like to use more then one MAX31856 module in my project. I know that to communicate with more then one modules I need to switch module´s CS input. For this libery, can I include more then one object of class Adafruit_MAX31856 changing just arduino´s CS output?  

Exemplo:
`Adafruit_MAX31856 object1 = Adafruit_MAX31856(CS1, DI, DO, CLK);`
`Adafruit_MAX31856 object2 = Adafruit_MAX31856(CS2, DI, DO, CLK);`
`Adafruit_MAX31856 object3 = Adafruit_MAX31856(CS3, DI, DO, CLK);`
`Adafruit_MAX31856 object4 = Adafruit_MAX31856(CS4, DI, DO, CLK);`
`Adafruit_MAX31856 object5 = Adafruit_MAX31856(CS5, DI, DO, CLK);`
`Adafruit_MAX31856 object6 = Adafruit_MAX31856(CS6, DI, DO, CLK);`

Thank you

Edson Xavier

**Comment by caternuson** [comment]
That seems correct for a software SPI case. Have you tried it?

**Comment by caternuson** [comment]
Closing due to lack of response.
