### ISSUE TITLE
Ultra Low Power OneShot and Read function

### ISSUE THREAD

**Issue by leanofis-iot** [adafruit/Adafruit_MAX31856#17]
There is a missing function for ultra low power sensor transmitter operations.
 
For the host mcu can go to sleep while max is in tCONV + delay(250) duration,
 using FAULT PIN;
The new read function (see only commented : oneShotTemperature();)

`/*!
    @brief  Read and return thermocouple tip temperature
    @returns Floating point temperature at end of thermocouple in Celsius
*/
/**************************************************************************/
float Adafruit_MAX31856::readNewThermocoupleTemperature(void) {
 // oneShotTemperature();

  int32_t temp24 = readRegister24(MAX31856_LTCBH_REG);
  if (temp24 & 0x800000) {
    temp24 |= 0xFF000000;  // fix sign
  }

  temp24 >>= 5;  // bottom 5 bits are unused

  float tempfloat = temp24;
  tempfloat *= 0.0078125;

  return tempfloat;
}

/**********************************************/`

The new function should be used like this;
MCU to MAX: oneShotTemperature();
MCU: go to SLEEP with configuration to wake up from FAULT(Alarm) PIN
MCU: WAKED if any FAULT
MCU to MAX: readNewThermocoupleTemperature();

I can further explain how an ultra low power sensor transmitter configurated with read_period and send_period..

**Comment by ladyada** [comment]
hi please submit it as a PR :)

**Comment by caternuson** [comment]
Little confused by what is wanted here. The MAX31856 has separate DRDY and FAULT pins. Are you wanting to wake on a fault or wake when a temperature conversion is complete?

**Comment by leanofis-iot** [comment]
Sorry, I can't go back in time.

**Comment by caternuson** [comment]
OK. Closing for now. Can reopen if more information becomes available.
