### ISSUE TITLE
Convert to BusIO

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_MAX31856#19]
This one too I guess? Currently directly using the SPI bus. Change to using SPIDevice from BusIO instead.

**Comment by caternuson** [comment]
Wow, the issue I opened in the MAX318**65** repo is also number 19. Fun. Deja vu fun.

**Comment by ladyada** [comment]
yah sure why not - long term all our libraries should use busio - that way when new platforms come out we dont have to do testing against each library!
