### ISSUE TITLE
Question: How to read/interpret MAX31856_VMODE_G8 and MAX31856_VMODE_G32 outputs? 

### ISSUE THREAD

**Issue by mpeaucelle** [adafruit/Adafruit_MAX31856#25]
Hello, 
Can you help in interpreting the output from MAX31856_VMODE_G8 and MAX31856_VMODE_G32 modes? 

In the MAX31865 datasheet, we only have the following description (p. 29): 
Selecting “Gain = 8” results in a full-scale input voltage range of ±78.125mV. “Gain = 32” results in a full-scale input voltage range of ±19.531mV. See the transfer functions from the Configuration 1 Register table. 

The transfer function from Configuration 1 Register table gives us: 
10xx = Voltage Mode, Gain = 8. Code = 8 x 1.6 x 217 x VIN
11xx = Voltage Mode, Gain = 32. Code = 32 x 1.6 x 217 x VIN

But I have no idea of how to interpret the returned value from the readThermocoupleTemperature() function for each mode. 
is it also multiplied by 0.0078125 as for temperature? 
Should I use another function or modify the readThermocoupleTemperature() to read the thermocouple register and apply the function provided in the Register Table? 

Thanks for your help,

**Comment by ladyada** [comment]
hihi for datasheet interpretation we recommend opening a ticket with maxim, their app engineers are experts at the chip and will give you definititve interpretations :)
