### ISSUE TITLE
Hardware SPI not working on ESP32

### ISSUE THREAD

**Issue by djObsidian** [adafruit/Adafruit_MAX31856#29]
- Arduino board:  **ESP32_DevkitC v4**

- Arduino IDE version (found in Arduino -> About Arduino menu):  **1.8.16**

- ESP32 Arduino core version **2.0.2**

Hardware SPI is not working, while software spi is working mostly ok.
Max31856 is connected to hspi pins, CS is 27
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/_images/esp32-devkitC-v4-pinout.png

I'm uploading https://github.com/adafruit/Adafruit_MAX31856/blob/master/examples/max31856_oneshot/max31856_oneshot.ino
MAX31856 is initialized with following code:
`SPIClass *ESP32_SPI = new SPIClass(HSPI);`
`Adafruit_MAX31856 maxthermo = Adafruit_MAX31856(27,ESP32_SPI);`

And the serial monitor just shows zero temperatures like:

Cold Junction Temp: 0.00
Thermocouple Temp: 0.00
Cold Junction Temp: 0.00
Thermocouple Temp: 0.00
Cold Junction Temp: 0.00
Thermocouple Temp: 0.00
Cold Junction Temp: 0.00
Thermocouple Temp: 0.00

After random time serial monitor shows actual temperature for several measures and then goes back to zeros
Cold Junction Temp: 20.77
Thermocouple Temp: 29.54
Cold Junction Temp: 20.73
Thermocouple Temp: 0.00
Cold Junction Temp: 20.73
Thermocouple Temp: 0.00
Cold Junction Temp: 20.73
Thermocouple Temp: 0.00
Cold Junction Temp: 20.73
Thermocouple Temp: 0.00
Cold Junction Temp: 20.77
Thermocouple Temp: 0.00
Cold Junction Temp: 20.77
Thermocouple Temp: 0.00
Cold Junction Temp: 20.77
Thermocouple Temp: 0.00
Cold Junction Temp: 20.77
Thermocouple Temp: 0.00
Cold Junction Temp: 20.84
Thermocouple Temp: 0.00
Cold Junction Temp: 0.02
Thermocouple Temp: 0.00

The problem is definitely with hardware spi, because with software SPI same example is working correctly

**Comment by ladyada** [comment]
hiya - can you show a photo of your wiring?

**Comment by djObsidian** [comment]
Yes, sure
![20220127_224213](https://user-images.githubusercontent.com/98160993/151432450-c9232b30-57e3-46a6-95d7-f71481c1fa00.jpg)

Here's also proof that with software SPI it works fine on same wiring
![Снимок экрана 2022-01-27 224439](https://user-images.githubusercontent.com/98160993/151432557-96d50091-1a0f-4da4-a215-21bd1a443072.png)

**Comment by caternuson** [comment]
Adafruit breakout ([link)](https://www.adafruit.com/product/3263) runs fine on Adafruit Feather ESP32 ([link](https://www.adafruit.com/product/3405)), FWIW. Same oneshot example from library with:
```cpp
Adafruit_MAX31856 maxthermo = Adafruit_MAX31856(27);
```

![Screenshot from 2022-01-27 12-41-51](https://user-images.githubusercontent.com/8755041/151440836-60711ba5-15bb-4329-95e6-18005670e20b.png)

**Comment by djObsidian** [comment]
@caternuson thanks, i got this working too. It turns out Adafruit Feather SPI pins are not HSPI, but VSPI. If i connect max31856 to VSPI port on ESP32 DevkitC, it works flawlessly. 


SPI | MOSI | MISO | CLK
-- | -- | -- | -- 
VSPI | GPIO 23 | GPIO 19 | GPIO 18
HSPI | GPIO 13 | GPIO 12 | GPIO 14
