### ISSUE TITLE
to add push button to select desired Thermocouple

### ISSUE THREAD

**Issue by DinoT84** [adafruit/Adafruit_MAX31856#30]
Sir,I tried to add push button to select desired Thermocouple,but failed even chages my codes many time could you please check it

#include <ShiftDisplay.h>
#include <Adafruit_MAX31856.h>
#include <EEPROM.h>

// Define pins for 7-segment display and button
const int DISPLAY_DATA_PIN = 2;
const int DISPLAY_LATCH_PIN = 3;
const int DISPLAY_CLOCK_PIN = 4;
const int BUTTON_PIN = 5;

// Create instance of ShiftDisplay and MAX31856 classes
ShiftDisplay display(DISPLAY_DATA_PIN, DISPLAY_LATCH_PIN, DISPLAY_CLOCK_PIN);
// Use software SPI: CS, DI, DO, CLK
Adafruit_MAX31856 maxthermo = Adafruit_MAX31856(10, 11, 12, 13);

// Define variables to store selected thermocouple type and EEPROM address
int selectedType = 0;
int eepromAddress = 0;

// Define thermocouple type names
const char* typeNames[] = {"B", "E", "J", "K", "N", "R", "S", "T"};
const int numTypes = sizeof(typeNames) / sizeof(typeNames[0]);

typedef Adafruit_MAX31856::thermocoupleTypes thermocoupletype;

void setup() {
  // Initialize serial communication for debugging
  Serial.begin(9600);

  // Initialize ShiftDisplay and MAX31856
 // display.begin(1);
  maxthermo.begin();

  // Read selected thermocouple type from EEPROM
  selectedType = EEPROM.read(eepromAddress);

  // Set initial display value
  display.set(typeNames[selectedType]);
  display.show(5000);
}

void loop() {
  // Check for button press and update selected thermocouple type
  if (digitalRead(BUTTON_PIN) == HIGH) {
    selectedType++;

    // Reset to B type if maximum type reached
    if (selectedType >= numTypes) {
      selectedType = 0;
    }

    // Write selected type to EEPROM
    EEPROM.write(eepromAddress, selectedType);

    // Update display with new value
    display.set(typeNames[selectedType]);
    display.show(5000);

    // Delay to debounce button
    delay(500);
  }

  // Read thermocouple temperature and print to serial monitor
  //float temperature = maxthermo.readThermocoupleTemperature(static_cast<Adafruit_MAX31856::thermocoupletype>(selectedType));
   float temperature = maxthermo.readThermocoupleTemperature(static_cast<thermocoupletype>(selectedType));

  Serial.print("Temperature: ");
  Serial.print(temperature);
  Serial.println(" C");

  // Delay before taking next reading
  delay(1000);
}

**Comment by DinoT84** [comment]
Following are errors:
typedef Adafruit_MAX31856::thermocoupleTypes thermocoupletype;

&

//float temperature = maxthermo.readThermocoupleTemperature(static_cast<Adafruit_MAX31856::thermocoupletype>(selectedType));
   float temperature = maxthermo.readThermocoupleTemperature(static_cast<thermocoupletype>(selectedType));

**Comment by caternuson** [comment]
Thermocouple types are already typedef'd with the `max31856_thermocoupletype_t` enum.

Use `setThermocoupleType()` to set the thermocouple type.

Closing since not a library issue.
