### ISSUE TITLE
Which Unit System?

### ISSUE THREAD

**Issue by alexPS92** [adafruit/Adafruit_MAX31856#5]
Hi all,

I've got a short question about the unit system used in this library. Is the output value in degree centigrade (°C) or degree Fahrenheit (°F)? If it is in °F it would explain some strange values I get.

Thanks,
Alex

**Comment by onlyfly34** [comment]
I got Celsius here on my Arduino.

**Comment by alexPS92** [comment]
Thanks for the Response, meanwhile I figured out that the thermocouples I bought are the problem.

So this thread can be closed.
