### ISSUE TITLE
speedMaximum of value 500000 in SPISettings doesn't work

### ISSUE THREAD

**Issue by onlyfly34** [adafruit/Adafruit_MAX31856#6]
As mentioned in the title, I set the value of speedMaximum to 5000000(5MHz) and my Arduino Uno hardware SPI works. Did I misunderstand anything?

**Comment by caternuson** [comment]
The current library hardwires the bus speed to 1MHz. Are there examples of how other BusIO based libraries have provided access the the SPI bus speed? Maybe just another parameter in ctor?

**Comment by ladyada** [comment]
@caternuson ya askin me?

**Comment by caternuson** [comment]
@ladyada Sure, if you want. Was just throwin' the question out there.

**Comment by caternuson** [comment]
Closing this for now.

Note that you can use different SPI clock speeds elsewhere in your code if you want. The BusIO SPI library will take care of switching to the settings used by this library. When this library uses the SPI bus, it will be at 1MHz.

If you actually need to access the MAX31856 on the SPI bus faster than 1MHz, please provide more info on the use case and why 1MHz is a limiting factor. Looks like the MAX31856 supports up to 5MHz, but 1MHz is hopefully fast enough. (conversions are on the order of 100ms)

![image](https://user-images.githubusercontent.com/8755041/82584349-3c037980-9b49-11ea-86b9-b4aaa281b19e.png)
