### ISSUE TITLE
Micropython version

### ISSUE THREAD

**Issue by eliotb** [adafruit/Adafruit_MAX31856#8]
Greetings,

I made a micropython driver for the MAX31856 (I have one of your boards).  Currently over here https://github.com/eliotb/micropython-max31856

As it is basically one file, would you consider adding it to this repo? If so, I can do the work of fork and pull request. (

**Comment by ladyada** [comment]
hiya, this is for Arduino only, so best to keep them separate, but thanks for pointing it out, others will find it useful! :)
